name: snyk scan
on:
  push:
    branches:
      - main
  pull_request_target:
    branches: 
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-20.04
    steps:
    # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      - name: Setup snyk
        uses: snyk/actions/setup@0.3.0
      - name: Snyk test
        run: snyk test --all-sub-projects --org=hypertrace --severity-threshold=low --policy-path=.snyk --configuration-matching='^runtimeClasspath$'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
